### ISSUE TITLE
Python STDOUT is captured instead of streamed in `bitrise run` output

### ISSUE THREAD

**Issue by ncreated** [bitrise-io/steps-script#22]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.

### Issue description

Hello 👋 

I'm recently building a complex automation in Python to run it on Bitrise. My Python script takes a long time to run and it prints a lot of useful logs on the way. To have better insights for debugging, I'd love to see those logs on Bitrise as soon as possible. Unfortunately, it appears to me that the `STDOUT` for Python scripts doesn't behave the same as for Bash scripts. 

When running Python, the `STDOUT` seems to be captured and only printed after the script completes.
When running Bash, the `STOUT` is nicely streamed to Bitrise log and can be seen as soon as the script starts.

### Steps to reproduce

Run this script:
```yml
    - script:
        title: Running Python script
        inputs:
        - runner_bin: /usr/bin/python3
        - content: |-
            import time

            print('one')
            time.sleep(2)
            print('two')
            time.sleep(2)
            print('three')

```
and observe the output of `bitrise run`:
- all values (`one`, `two`, `three`) will be printed after `~4s` at once - when the script completes.

### Expected behaviour

I'd expect Python script to be run similar to bash script:
```yml
    - script:
        title: Running Bash script
        inputs:
        - runner_bin: /bin/bash
        - content: |-
            echo one
            sleep 2
            echo two
            sleep 2
            echo three
```
where each value can be seen early in `bitrise run` output (`one`, `2s` later: `two`, `2s` later: `three`).

This could be a FR rather than a bug 🐞, but I report it here as the behaviour differs per `runner_bin`. 

**Is there any workaround that I could install to see streamed Python `STDOUT` in Bitrise log?** I tried launching python script form a bash script (`python3 script.py`), but unfortunately this doesn't help.
